AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-artifacts-96ece076beabc628/8da78a9af8875a099bd015c3414deead
      Handler: example.Handler
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 30
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
      Layers:
      - Ref: libs
      Events:
        s3Notification:
          Type: S3
          Properties:
            Bucket:
              Ref: bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: inbound/
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: s3-java-lib
      Description: Dependencies for the Java S3 sample app.
      ContentUri: s3://lambda-artifacts-96ece076beabc628/a1cfcf1b4d7b1d10e651a2653e159ad4
      CompatibleRuntimes:
      - java8
